## Basic Theme Info
name: WVU Brand Patterns
description: This is the WVU Brand Patterns theme built for CleanSlate. Originally authored by Adam Glenn.

## Attributes, Data and Variables
custom_site_attributes:
  # For Google Search Console
  - apply_link_1
  - apply_link_1_url
  - apply_link_2
  - apply_link_2_url
  - apply_link_3
  - apply_link_3_url
  - classes_card
  - classes_wvu-action-hero--sitewide
  - classes_wvu-adverts--anywhere
  - classes_wvu-adverts__card
  - classes_wvu-adverts__heading
  - classes_wvu-backpage-header__h1
  - classes_wvu-breadcrumbs
  - classes_wvu-directory--anywhere
  - classes_wvu-event-agenda--anywhere
  - classes_wvu-featurettes--anywhere
  - classes_wvu-featurettes-2--anywhere
  - classes_wvu-footer
  - classes_wvu-footer-links
  - default_content_01
  - default_content_02
  - default_content_03
  - facebook_url
  - flickr_url
  - github_url
  - google_site_verification
  - has_alternate_logo
  - has_co_brand
  - has_standard_footer
  - hide_instructions
  - instagram_url
  - is_demo_site
  - jquery_defer
  - linkedin_url
  - masthead_college_link_address
  - masthead_college_link_title
  - masthead_color
  - masthead_link_2_address
  - masthead_link_2_title
  - masthead_logo_url
  - masthead_title
  - nav_depth
  - nav_dropdowns
  - syndication_url
  - show_apply_links
  - show_instructions
  - sidebar_sticky_site
  - slot_00_masthead
  - slot_00_nav
  - twitter_handle
  - twitter_url
  - twitter_widget_id
  - youtube_url

## Template Config
# Specify which templates show up by default when creating a page
default_templates:
  content: backpage
  blog: blog_index
  article: blog_article
  error: backpage

## Optimizations
css:
  # Turn CSS compression on/off.
  compress: true
js:
  # Turn JavaScript compression and mangling on/off
  compress: true
  mangle: true
