## Basic Theme Info
name: WVU Brand Patterns
description: This is the WVU Brand Patterns theme built for CleanSlate. Originally authored by Adam Glenn.

## Attributes, Data and Variables
custom_site_attributes:
  # For Google Search Console
  - apply_link_1
  - apply_link_1_url
  - apply_link_2
  - apply_link_2_url
  - apply_link_3
  - apply_link_3_url
  - classes_wvu_backpage_header__h1
  - co_brand_subtitle
  - default_content_01
  - default_content_02
  - default_content_03
  - facebook_url
  - flickr_url
  - github_url
  - google_site_verification
  - has_alternate_logo
  - has_co_brand
  - has_standard_footer
  - hide_instructions
  - instagram_url
  - is_demo_site
  - jquery_defer
  - linkedin_url
  - masthead_college_link_address
  - masthead_college_link_title
  - masthead_color
  - masthead_link_2_address
  - masthead_link_2_title
  - masthead_logo_url
  - masthead_title
  - nav_dropdowns
  - syndication_url
  - show_apply_links
  - show_instructions
  - sidebar_sticky_site
  - slot_00_masthead
  - slot_00_nav
  - slot_11
  - slot_11_custom
  - slot_11_where_to_display
  - slot_11_is_main
  - slot_11_align
  - slot_11_featurettes_style
  - slot_11_featurettes_id
  - slot_11_limit
  - slot_11_number
  - slot_11_loop_by
  - slot_11_loop_labels_match
  - slot_11_loop_order
  - slot_11_show_hidden
  - slot_12
  - slot_12_custom
  - slot_12_where_to_display
  - slot_12_is_main
  - slot_12_align
  - slot_12_featurettes_style
  - slot_12_featurettes_id
  - slot_12_limit
  - slot_12_number
  - slot_12_loop_by
  - slot_12_loop_labels_match
  - slot_12_loop_order
  - slot_12_show_hidden
  - slot_13
  - slot_13_custom
  - slot_13_where_to_display
  - slot_13_is_main
  - slot_13_align
  - slot_13_featurettes_style
  - slot_13_featurettes_id
  - slot_13_limit
  - slot_13_number
  - slot_13_loop_by
  - slot_13_loop_labels_match
  - slot_13_loop_order
  - slot_13_show_hidden
  - twitter_handle
  - twitter_url
  - twitter_widget_id
  - youtube_url

## Template Config
# Specify which templates show up by default when creating a page
default_templates:
  content: backpage
  blog: blog_index
  article: blog_article
  error: error

## Optimizations
css:
  # Turn CSS compression on/off.
  compress: true
js:
  # Turn JavaScript compression and mangling on/off
  compress: true
  mangle: true
